### ISSUE TITLE
Server wont start on linux

### ISSUE THREAD

**Issue by csalter104** [AllTheMods/Server-Scripts#83]
sh '/opt/minecraft/skyfactory4/serverstart.sh' 
/opt/minecraft/skyfactory4/serverstart.sh: 36: Syntax error: "(" unexpected (expecting "then")

**Comment by NexusXe** [comment]
I realize this is a stale issue, but for those encountering this issue in the future:
Make sure you're running the server in `bash`. The kernel will (by default) handle this due to the shebang, but running the command as something like `sh ./serverstart.sh` will result in error.

Simply running it as `./serverstart.sh` will resolve this issue.
